### ISSUE TITLE
APIリファレンスのロゴ画像がリンク切れ

### ISSUE THREAD

**Issue by nabeix** [akashic-games/akashic-games.github.io#4]
https://akashic-games.github.io/reference/akashic-engine/index.html
https://akashic-games.github.io/reference/akashic-timeline/index.html

**Comment by lambdataro** [comment]
ありがとうございます。
[npm のページ](https://www.npmjs.com/package/@akashic/akashic-engine) でも同様の問題が発生しているので合わせて対応します。

**Comment by lambdataro** [comment]
遅くなりましたが、修正完了しました。
